apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  ports:
  - port: 9084        # Custom port exposed to the K8s cluster
    targetPort: 8086  # Routes traffic to 8086 inside the pod
  selector:
    app: influxdb

